plugins {
    id "java-library"
    id "com.gradleup.shadow" version "9.6.0"
}

group = "dev.castiel"
version = "1.0.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:26.2.build.62-beta"
    implementation "org.yaml:snakeyaml:2.6"
    api "com.zaxxer:HikariCP:4.0.3"
    api "com.github.cryptomorin:XSeries:13.7.1"
    testImplementation "io.papermc.paper:paper-api:26.2.build.62-beta"
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.4"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

configurations.configureEach {
    resolutionStrategy.force "com.github.cryptomorin:XSeries:13.7.1"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(25)
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveClassifier.set("")
    relocate "com.zaxxer.hikari", "dev.castiel.lib.libs.hikari"
    relocate "org.yaml.snakeyaml", "dev.castiel.lib.libs.snakeyaml"
}
